export {
  AgentAdapterError,
  AgentSessionPersistenceError,
  AgentSessionRuntimeOwnershipError,
  EntityAlreadyExistsError,
  EntityNotFoundError,
  GitRepositoryInspectionError,
  ProjectOpenError,
  PtyRuntimeError,
  TaskWorktreeLifecycleError,
  TaskWorktreeMetadataConflictError,
  TaskWorktreePersistenceError,
  TaskExecutionStartError,
  type EntityKind,
  type AgentAdapterFailureReason,
  type GitRepositoryInspectionFailure,
  type ProjectOpenFailure,
  type TaskWorktreeLifecycleFailure,
  type TaskExecutionStartStage,
} from './errors';
export {
  AgentSessionCoordinator,
  type AgentSessionTerminalAttachment,
  type AgentSessionCoordinatorDependencies,
  type AttachAgentSessionTerminalInput,
  type ReportAgentSessionStatusInput,
  type StartAgentSessionInput,
  type StopAgentSessionInput,
} from './agent-session-coordinator';
export { inspectAgent, launchAgent, type LaunchAgentInput } from './agent-launch';
export { listRecentProjects, openProject, type OpenProjectInput } from './project-management';
export { createProject } from './project-use-cases';
export type {
  AgentAdapter,
  AgentAvailability,
  AgentCapabilities,
  AgentLaunchCommand,
  AgentLaunchRequest,
  AgentVersion,
  AgentSessionRepository,
  DiscoveredProject,
  GitBaseBranch,
  GitHead,
  GitRepositoryInspection,
  GitRepositoryInspector,
  GitRepositorySnapshot,
  GitWorkingTreeStatus,
  GitTaskWorktreeLifecycle,
  InspectGitTaskWorktreeInput,
  LocalProject,
  LocalProjectLocator,
  PtyHandle,
  PtyLaunchSpec,
  PtyRuntime,
  PtyRuntimeEvent,
  PtyRuntimeEventSink,
  PtyRuntimeFailureReason,
  PtyRuntimeOperation,
  PtyTerminalSize,
  ProjectCatalog,
  ProjectDiscovery,
  ProjectRepository,
  RecordProjectOpenInput,
  TaskRepository,
  TaskWorktree,
  TaskWorktreeCleanupResult,
  TaskWorktreeEnsureResult,
  TaskWorktreeInspection,
  TaskWorktreeLifecycleState,
  TaskWorktreeRecord,
  TaskWorktreeRepository,
  TaskWorktreeStatus,
} from './ports';
export { createTask, transitionTask, type TransitionTaskInput } from './task-use-cases';
export {
  startTaskExecution,
  type StartTaskExecutionDependencies,
  type StartTaskExecutionInput,
  type TaskExecutionStartResult,
} from './task-execution';
export {
  cleanupTaskWorktree,
  ensureTaskWorktree,
  inspectTaskWorktree,
  type InspectTaskWorktreeResult,
  type TaskWorktreeInput,
} from './task-worktree-use-cases';
